name: "Conditional Deployment"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - "!**/readme.md"
      - "project/**"
  push:
    branches:
      - main
    paths:
      - "!**/readme.md"
      - "project/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      RUN_DEPLOYMENT_1:
        type: boolean
        description: 'Run Deployment 1'
        required: true
      RUN_DEPLOYMENT_2:
        type: boolean
        description: 'Run Deployment 2'
        required: true

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployment_1:
    if: github.event.inputs.RUN_DEPLOYMENT_1 == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo conditional_deployment_1 executing - ${{ github.event.inputs.RUN_DEPLOYMENT_1 }}

  deployment_2:
    if: github.event.inputs.RUN_DEPLOYMENT_2 == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo conditional_deployment_2 executing - ${{ github.event.inputs.RUN_DEPLOYMENT_2 }}
