on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - "!**/readme.md"
      - "project/**"
  push:
    branches:
      - main
    paths:
      - "!**/readme.md"
      - "project/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  jobs:
    conditional_deploy_1:
      if: false == true
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo conditional_deploy_1 executing

    conditional_deploy_2:
      if: true == true
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo conditional_deploy_2 executing
